apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}"
  namespace: "{{ .Values.general.namespace }}-{{ .Values.general.stage }}"
data:
  index.html: |
    This is our showcase in apache!
